// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package types

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DomainRegistry struct {
	_tab flatbuffers.Table
}

func GetRootAsDomainRegistry(buf []byte, offset flatbuffers.UOffsetT) *DomainRegistry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DomainRegistry{}
	x.Init(buf, n+offset)
	return x
}

func FinishDomainRegistryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDomainRegistry(buf []byte, offset flatbuffers.UOffsetT) *DomainRegistry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DomainRegistry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDomainRegistryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DomainRegistry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DomainRegistry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DomainRegistry) Root(obj *TrieNode) *TrieNode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TrieNode)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DomainRegistryStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DomainRegistryAddRoot(builder *flatbuffers.Builder, root flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(root), 0)
}
func DomainRegistryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
