// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package types

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FeeSummary struct {
	_tab flatbuffers.Table
}

func GetRootAsFeeSummary(buf []byte, offset flatbuffers.UOffsetT) *FeeSummary {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FeeSummary{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *FeeSummary) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FeeSummary) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FeeSummary) TotalFees() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FeeSummary) MutateTotalFees(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *FeeSummary) TotalAggregator() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FeeSummary) MutateTotalAggregator(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *FeeSummary) TotalBurned() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FeeSummary) MutateTotalBurned(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *FeeSummary) TotalEpoch() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FeeSummary) MutateTotalEpoch(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func FeeSummaryStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func FeeSummaryAddTotalFees(builder *flatbuffers.Builder, totalFees uint64) {
	builder.PrependUint64Slot(0, totalFees, 0)
}
func FeeSummaryAddTotalAggregator(builder *flatbuffers.Builder, totalAggregator uint64) {
	builder.PrependUint64Slot(1, totalAggregator, 0)
}
func FeeSummaryAddTotalBurned(builder *flatbuffers.Builder, totalBurned uint64) {
	builder.PrependUint64Slot(2, totalBurned, 0)
}
func FeeSummaryAddTotalEpoch(builder *flatbuffers.Builder, totalEpoch uint64) {
	builder.PrependUint64Slot(3, totalEpoch, 0)
}
func FeeSummaryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
