// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package types

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SnapshotResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSnapshotResponse(buf []byte, offset flatbuffers.UOffsetT) *SnapshotResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SnapshotResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSnapshotResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSnapshotResponse(buf []byte, offset flatbuffers.UOffsetT) *SnapshotResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SnapshotResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSnapshotResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SnapshotResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SnapshotResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SnapshotResponse) RequestId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotResponse) MutateRequestId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *SnapshotResponse) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SnapshotResponse) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SnapshotResponse) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SnapshotResponse) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *SnapshotResponse) UncompressedSize() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotResponse) MutateUncompressedSize(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func SnapshotResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SnapshotResponseAddRequestId(builder *flatbuffers.Builder, requestId uint64) {
	builder.PrependUint64Slot(0, requestId, 0)
}
func SnapshotResponseAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func SnapshotResponseStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SnapshotResponseAddUncompressedSize(builder *flatbuffers.Builder, uncompressedSize uint64) {
	builder.PrependUint64Slot(2, uncompressedSize, 0)
}
func SnapshotResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
