// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package types

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SnapshotRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSnapshotRequest(buf []byte, offset flatbuffers.UOffsetT) *SnapshotRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SnapshotRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSnapshotRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSnapshotRequest(buf []byte, offset flatbuffers.UOffsetT) *SnapshotRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SnapshotRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSnapshotRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SnapshotRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SnapshotRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SnapshotRequest) RequestId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotRequest) MutateRequestId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func SnapshotRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SnapshotRequestAddRequestId(builder *flatbuffers.Builder, requestId uint64) {
	builder.PrependUint64Slot(0, requestId, 0)
}
func SnapshotRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
